# Quantium Virtual Internship - Retail Strategy and Analytics - Task 1

## Load required libraries and datasets

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [2]:
customerData=pd.read_csv("QVI_purchase_behaviour.csv")

In [3]:
transactionData = pd.read_excel('QVI_transaction_data.xlsx', engine='openpyxl')

In [4]:
transactionData.head()

,DATE,STORE_NBR,LYLTY_CARD_NBR,TXN_ID,PROD_NBR,PROD_NAME,PROD_QTY,TOT_SALES
0,43390,1,1000,1,5,Natural Chip Compny SeaSalt175g,2,6.0
1,43599,1,1307,348,66,CCs Nacho Cheese 175g,3,6.3
2,43605,1,1343,383,61,Smiths Crinkle Cut Chips Chicken 170g,2,2.9
3,43329,2,2373,974,69,Smiths Chip Thinly S/Cream&Onion 175g,5,15.0
4,43330,2,2426,1038,108,Kettle Tortilla ChpsHny&Jlpno Chili 150g,3,13.8

In [5]:
customerData.head()

   LYLTY_CARD_NBR               LIFESTAGE PREMIUM_CUSTOMER
0            1000   YOUNG SINGLES/COUPLES          Premium
1            1002   YOUNG SINGLES/COUPLES       Mainstream
2            1003          YOUNG FAMILIES           Budget
3            1004   OLDER SINGLES/COUPLES       Mainstream
4            1005  MIDAGE SINGLES/COUPLES       Mainstream

# Exploratory data analysis

### Examining transaction data

In [6]:
transactionData.dtypes

DATE                int64
STORE_NBR           int64
LYLTY_CARD_NBR      int64
TXN_ID              int64
PROD_NBR            int64
PROD_NAME             str
PROD_QTY            int64
TOT_SALES         float64
dtype: object

In [7]:
#We can see that the date column is in an integer format. Let's change this to a date format.
transactionData['DATE'] = pd.to_datetime(transactionData['DATE'], origin='1899-12-30', unit='D')

In [10]:
unique_prod=transactionData['PROD_NAME'].unique()

In [11]:
print(unique_prod)

<StringArray>
[  'Natural Chip        Compny SeaSalt175g',
                 'CCs Nacho Cheese    175g',
   'Smiths Crinkle Cut  Chips Chicken 170g',
   'Smiths Chip Thinly  S/Cream&Onion 175g',
 'Kettle Tortilla ChpsHny&Jlpno Chili 150g',
 'Old El Paso Salsa   Dip Tomato Mild 300g',
 'Smiths Crinkle Chips Salt & Vinegar 330g',
    'Grain Waves         Sweet Chilli 210g',
  'Doritos Corn Chip Mexican Jalapeno 150g',
    'Grain Waves Sour    Cream&Chives 210G',
 ...
         'Doritos Cheese      Supreme 330g',
      'Smiths Crinkle Cut  Snag&Sauce 150g',
   'WW Sour Cream &OnionStacked Chips 160g',
                 'RRD Lime & Pepper   165g',
   'Natural ChipCo Sea  Salt & Vinegr 175g',
    'Red Rock Deli Chikn&Garlic Aioli 150g',
      'RRD SR Slow Rst     Pork Belly 150g',
                 'RRD Pc Sea Salt     165g',
       'Smith Crinkle Cut   Bolognese 150g',
                 'Doritos Salsa Mild  300g']
Length: 114, dtype: str

In [12]:
chips=transactionData[transactionData['PROD_NAME'].str.contains('Chips',case=False, na=False)]

In [13]:
print(chips)

             DATE  STORE_NBR  LYLTY_CARD_NBR  TXN_ID  PROD_NBR  \
2      2019-05-20          1            1343     383        61
6      2019-05-16          4            4149    3333        16
10     2019-05-17          7            7215    7176        16
14     2019-05-15         19           19272   16686        44
33     2019-05-18         45           45220   41651        22
...           ...        ...             ...     ...       ...
264809 2018-08-24        271          271051  268506        47
264815 2018-11-04        271          271193  269365        33
264816 2019-05-29        271          271193  269366        75
264826 2019-03-25        272          272194  269908        75
264830 2018-11-12        272          272319  270087        44

                                       PROD_NAME  PROD_QTY  TOT_SALES
2         Smiths Crinkle Cut  Chips Chicken 170g         2        2.9
6       Smiths Crinkle Chips Salt & Vinegar 330g         1        5.7
10      Smiths Crinkle Chips Salt & Vinegar 330g         1        5.7
14                Thins Chips Light&  Tangy 175g         1        3.3
33        Thins Chips         Originl saltd 175g         1        3.3
...                                          ...       ...        ...
264809         Doritos Corn Chips  Original 170g         2        8.8
264815  Cobs Popd Swt/Chlli &Sr/Cream Chips 110g         2        7.6
264816            Cobs Popd Sea Salt  Chips 110g         2        7.6
264826            Cobs Popd Sea Salt  Chips 110g         2        7.6
264830            Thins Chips Light&  Tangy 175g         2        6.6

[49770 rows x 8 columns]