# Quantium Virtual Internship - Retail Strategy and Analytics - Task 1

## Load required libraries and datasets

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [2]:
customerData=pd.read_csv("QVI_purchase_behaviour.csv")

In [3]:
transactionData = pd.read_excel('QVI_transaction_data.xlsx', engine='openpyxl')

In [4]:
transactionData.head()

,DATE,STORE_NBR,LYLTY_CARD_NBR,TXN_ID,PROD_NBR,PROD_NAME,PROD_QTY,TOT_SALES
0,43390,1,1000,1,5,Natural Chip Compny SeaSalt175g,2,6.0
1,43599,1,1307,348,66,CCs Nacho Cheese 175g,3,6.3
2,43605,1,1343,383,61,Smiths Crinkle Cut Chips Chicken 170g,2,2.9
3,43329,2,2373,974,69,Smiths Chip Thinly S/Cream&Onion 175g,5,15.0
4,43330,2,2426,1038,108,Kettle Tortilla ChpsHny&Jlpno Chili 150g,3,13.8

In [5]:
customerData.head()

   LYLTY_CARD_NBR               LIFESTAGE PREMIUM_CUSTOMER
0            1000   YOUNG SINGLES/COUPLES          Premium
1            1002   YOUNG SINGLES/COUPLES       Mainstream
2            1003          YOUNG FAMILIES           Budget
3            1004   OLDER SINGLES/COUPLES       Mainstream
4            1005  MIDAGE SINGLES/COUPLES       Mainstream

# Exploratory data analysis

### Examining transaction data

In [6]:
transactionData.dtypes

DATE                int64
STORE_NBR           int64
LYLTY_CARD_NBR      int64
TXN_ID              int64
PROD_NBR            int64
PROD_NAME             str
PROD_QTY            int64
TOT_SALES         float64
dtype: object

In [7]:
#We can see that the date column is in an integer format. Let's change this to a date format.
transactionData['DATE'] = pd.to_datetime(transactionData['DATE'], origin='1899-12-30', unit='D')

In [8]:
unique_prod=transactionData['PROD_NAME'].unique()

In [9]:
print(unique_prod)

<StringArray>
[  'Natural Chip        Compny SeaSalt175g',
                 'CCs Nacho Cheese    175g',
   'Smiths Crinkle Cut  Chips Chicken 170g',
   'Smiths Chip Thinly  S/Cream&Onion 175g',
 'Kettle Tortilla ChpsHny&Jlpno Chili 150g',
 'Old El Paso Salsa   Dip Tomato Mild 300g',
 'Smiths Crinkle Chips Salt & Vinegar 330g',
    'Grain Waves         Sweet Chilli 210g',
  'Doritos Corn Chip Mexican Jalapeno 150g',
    'Grain Waves Sour    Cream&Chives 210G',
 ...
         'Doritos Cheese      Supreme 330g',
      'Smiths Crinkle Cut  Snag&Sauce 150g',
   'WW Sour Cream &OnionStacked Chips 160g',
                 'RRD Lime & Pepper   165g',
   'Natural ChipCo Sea  Salt & Vinegr 175g',
    'Red Rock Deli Chikn&Garlic Aioli 150g',
      'RRD SR Slow Rst     Pork Belly 150g',
                 'RRD Pc Sea Salt     165g',
       'Smith Crinkle Cut   Bolognese 150g',
                 'Doritos Salsa Mild  300g']
Length: 114, dtype: str

In [12]:
pot_chips=transactionData[transactionData['PROD_NAME'].str.contains(r'potato.*Chips|chips.*potato',case=False, na=False)]

In [13]:
print(pot_chips)

             DATE  STORE_NBR  LYLTY_CARD_NBR  TXN_ID  PROD_NBR  \
86     2019-05-19        115          115381  118981        29
97     2018-08-16        128          128231  132121        28
211    2018-11-01          1            1348     390        28
221    2018-09-23          2            2203     805        28
254    2018-08-06          4            4016    2713        28
...           ...        ...             ...     ...       ...
264557 2019-02-02        259          259226  258909        29
264667 2019-06-29        265          265032  263333        29
264695 2019-01-22        266          266013  263849        29
264710 2019-01-20        266          266111  263947        28
264770 2019-03-02        269          269203  266265        28

                                   PROD_NAME  PROD_QTY  TOT_SALES
86            French Fries Potato Chips 175g         1        3.0
97      Thins Potato Chips  Hot & Spicy 175g         1        3.3
211     Thins Potato Chips  Hot & Spicy 175g         1        3.3
221     Thins Potato Chips  Hot & Spicy 175g         1        3.3
254     Thins Potato Chips  Hot & Spicy 175g         2        6.6
...                                      ...       ...        ...
264557        French Fries Potato Chips 175g         2        6.0
264667        French Fries Potato Chips 175g         1        3.0
264695        French Fries Potato Chips 175g         1        3.0
264710  Thins Potato Chips  Hot & Spicy 175g         1        3.3
264770  Thins Potato Chips  Hot & Spicy 175g         2        6.6

[4647 rows x 8 columns]