# Quantium Virtual Internship - Retail Strategy and Analytics - Task 1

## Load required libraries and datasets

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [2]:
customerData=pd.read_csv("QVI_purchase_behaviour.csv")

In [3]:
import sys
!"{sys.executable}" -m pip install openpyxl

Requirement already satisfied: openpyxl in D:\Jupyter lab\myenv\Lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in D:\Jupyter lab\myenv\Lib\site-packages (from openpyxl) (2.0.0)

In [4]:
transactionData = pd.read_excel('QVI_transaction_data.xlsx', engine='openpyxl')

In [5]:
transactionData.head()

,DATE,STORE_NBR,LYLTY_CARD_NBR,TXN_ID,PROD_NBR,PROD_NAME,PROD_QTY,TOT_SALES
0,43390,1,1000,1,5,Natural Chip Compny SeaSalt175g,2,6.0
1,43599,1,1307,348,66,CCs Nacho Cheese 175g,3,6.3
2,43605,1,1343,383,61,Smiths Crinkle Cut Chips Chicken 170g,2,2.9
3,43329,2,2373,974,69,Smiths Chip Thinly S/Cream&Onion 175g,5,15.0
4,43330,2,2426,1038,108,Kettle Tortilla ChpsHny&Jlpno Chili 150g,3,13.8

In [6]:
customerData.head()

   LYLTY_CARD_NBR               LIFESTAGE PREMIUM_CUSTOMER
0            1000   YOUNG SINGLES/COUPLES          Premium
1            1002   YOUNG SINGLES/COUPLES       Mainstream
2            1003          YOUNG FAMILIES           Budget
3            1004   OLDER SINGLES/COUPLES       Mainstream
4            1005  MIDAGE SINGLES/COUPLES       Mainstream

# Exploratory data analysis

### Examining transaction data

In [7]:
transactionData.dtypes

DATE                int64
STORE_NBR           int64
LYLTY_CARD_NBR      int64
TXN_ID              int64
PROD_NBR            int64
PROD_NAME             str
PROD_QTY            int64
TOT_SALES         float64
dtype: object

In [8]:
#We can see that the date column is in an integer format. Let's change this to a date format.
transactionData['DATE'] = pd.to_datetime(transactionData['DATE'], origin='1899-12-30', unit='D')